# Homebrew packages for macOS
# このファイルを ~/.Brewfile にコピーするか、run_onchange_update.sh.tmpl で参照される

# Taps
tap "homebrew/bundle"
tap "homebrew/cask"

# CLI tools
brew "git"
brew "neovim"
brew "tmux"
brew "fzf"
brew "ripgrep"
brew "fd"
brew "bat"
brew "eza"
brew "zoxide"

# Casks (GUI アプリ)
# cask "visual-studio-code"
# cask "iterm2"
